### ISSUE TITLE
please update php version

### ISSUE THREAD

**Issue by wetlyrics** [yobasystems/alpine-php-wordpress#4]
using this git:
https://github.com/codecasts/php-alpine

or is there any way to update the php to the latest one or update nginx to mainline ??

**Comment by dominictayloruk** [comment]
The version in my image is using the official repos, which integrate with all the container security scanning and is also a later version than the one you have referenced;

https://pkgs.alpinelinux.org/packages?name=php7&branch=v3.8&arch=x86_64
alpine 3.8 : version 7.2.13-r0

https://github.com/codecasts/php-alpine
alpine 3.8 : version 7.2.12

In regards to nginx mainline, again i'm using the official alpine repos which contain the stable release rather than mainline but your free to use the `FROM yobasystems/alpine-nginx` image which uses the mainline version built from source.

**Comment by dominictayloruk** [comment]
`docker pull yobasystems/alpine-php-wordpress:special`

Use mainline nginx built from source.
